const AUTHENTICATE_ROUTE = {
  LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
  REGISTER: '@AUTHENTICATE_ROUTE/REGISTER',
};

const APP_ROUTE = {
  MAIN_TAB: '@APP_ROUTE/MAIN_TAB',
};

const HOME_ROUTE = {
  ROOT: '@HOME_ROUTE/ROOT',
  HOME_SCREEN: '@HOME_ROUTE/HOME_SCREEN',
};

const SETTING_ROUTE = {
  ROOT: '@SETTING_ROUTE/ROOT',
  SETTING_SCREEN : '@SETTING_ROUTE/SETTING_SCREEN'
};

const BOTTOMTAB_ROUTE = {
  ROOT: '@BOTTOMTAB_ROUTE/ROOT',
  BOTTOMTAB_SCREEN : '@BOTTOMTAB_ROUTE/BOTTOMTAB_SCREEN'
};

const MENU_ROUTE = {
  MENU_SCREEN : '@MENU_ROUTE/MENU_SCREEN',
  ROOT: '@MENU_ROUTE/ROOT',
};

const POLICY_ROUTE = {
  ROOT : '@POLICY_ROUTE/ROOT',
  POLICY_SCREEN : '@POLICY_ROUTE/POLICY_SCREEN'
};

const ORDER_ROUTE = {
  ROOT : '@ORDER_ROUTE/ROOT',
  ORDER_SCREEN : '@ORDER_ROUTE/ORDER_SCREEN'
}

const PAYMENT_ROUTE = {
  ROOT : '@PAYMENT_ROUTE/ROOT',
  PAYMENT_SCREEN : '@PAYMENT_ROUTE/PAYMENT_SCREEN'
}
const TAB_NAVIGATION_ROOT = {
  HOME_ROUTE,
  SETTING_ROUTE,
  BOTTOMTAB_ROUTE,
  MENU_ROUTE,
  AUTHENTICATE_ROUTE,
  POLICY_ROUTE,
  ORDER_ROUTE,
  PAYMENT_ROUTE
};

export { APP_ROUTE, TAB_NAVIGATION_ROOT, AUTHENTICATE_ROUTE, HOME_ROUTE,  BOTTOMTAB_ROUTE, MENU_ROUTE , POLICY_ROUTE , ORDER_ROUTE, PAYMENT_ROUTE};
